### ISSUE TITLE
Setting button

### ISSUE THREAD

**Issue by mjsibbald** [AndreaMelle/iosvr#1]
Is the settings button implemented? I cannot find it. 

Cheers,

Maik

**Comment by AndreaMelle** [comment]
Which settings button?

**Comment by mjsibbald** [comment]
To load the qr code scanner? Probably not implemented? 

Sucks the current cardboard is unity for ios…

**Comment by AndreaMelle** [comment]
Oh, I see what you mean.
No, this does not implement the features that the recent google cardboard plugin has.

It's a minimal set of functionalities.

If you need the full google cardboard stuff, use the Unity plugin which is compatible for both iOS and android. You'll find it on Google cardboard website.
