### ISSUE TITLE
HLS (HTTP live streaming)?

### ISSUE THREAD

**Issue by gnestor** [AndreaMelle/iosvr#3]
How much work would it be to support remote video playback using this library?

**Comment by AndreaMelle** [comment]
Strictly speaking, zero work.
Video is decoded through avfoundation, hence you can pass a url to a local or remote video, or a url to a hls playlist.

The challenges I'm aware of (I've tried already) are beyond the client: get a backend up and running that can produce and serve live video in equirectangular format, and bandwidth, of course. Low quality streams are much much more annoying in VR. ;)

**Comment by gnestor** [comment]
Great to know. Thanks @AndreaMelle!
